export type Vehicle = {
  registrationNumber: string
  taxStatus: string
  taxDueDate: Date
  motStatus: string
  make: string
  yearOfManufacture: number
  engineCapacity: number
  co2Emissions: number
  fuelType: string
  markedForExport: boolean
  colour: string
  typeApproval: string
  euroStatus: string
  dateOfLastV5CIssued: Date
  motExpiryDate: Date
  wheelplan: string
  monthOfFirstRegistration: Date
}

export const VEHICLE_DATA: { [key: string]: Vehicle } = {
  AE68FWG: {
    registrationNumber: "AE68FWG",
    taxStatus: "Taxed",
    taxDueDate: new Date("2024-10-15"),
    motStatus: "Valid",
    make: "VOLVO",
    yearOfManufacture: 2018,
    engineCapacity: 1969,
    co2Emissions: 169,
    fuelType: "PETROL",
    markedForExport: false,
    colour: "BLACK",
    typeApproval: "M1",
    euroStatus: "EURO 6 AG",
    dateOfLastV5CIssued: new Date("2023-10-15"),
    motExpiryDate: new Date("2024-09-13"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2018-10"),
  },
  BX19UDF: {
    registrationNumber: "BX19UDF",
    taxStatus: "Taxed",
    taxDueDate: new Date("2025-03-20"),
    motStatus: "Valid",
    make: "FORD",
    yearOfManufacture: 2019,
    engineCapacity: 1499,
    co2Emissions: 95,
    fuelType: "DIESEL",
    markedForExport: false,
    colour: "WHITE",
    typeApproval: "N1",
    euroStatus: "EURO 6 DG",
    dateOfLastV5CIssued: new Date("2024-03-20"),
    motExpiryDate: new Date("2025-03-19"),
    wheelplan: "4X2",
    monthOfFirstRegistration: new Date("2019-03"),
  },
  CF16TYR: {
    registrationNumber: "CF16TYR",
    taxStatus: "Taxed",
    taxDueDate: new Date("2024-08-12"),
    motStatus: "Valid",
    make: "BMW",
    yearOfManufacture: 2016,
    engineCapacity: 1998,
    co2Emissions: 134,
    fuelType: "PETROL",
    markedForExport: false,
    colour: "BLUE",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2023-08-12"),
    motExpiryDate: new Date("2024-08-11"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2016-08"),
  },
  DN17YUI: {
    registrationNumber: "DN17YUI",
    taxStatus: "Taxed",
    taxDueDate: new Date("2024-05-28"),
    motStatus: "Valid",
    make: "AUDI",
    yearOfManufacture: 2017,
    engineCapacity: 1968,
    co2Emissions: 154,
    fuelType: "DIESEL",
    markedForExport: false,
    colour: "RED",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2023-05-28"),
    motExpiryDate: new Date("2024-05-27"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2017-05"),
  },
  EK18LOP: {
    registrationNumber: "EK18LOP",
    taxStatus: "Taxed",
    taxDueDate: new Date("2025-06-16"),
    motStatus: "Valid",
    make: "MERCEDES-BENZ",
    yearOfManufacture: 2018,
    engineCapacity: 2143,
    co2Emissions: 144,
    fuelType: "DIESEL",
    markedForExport: false,
    colour: "SILVER",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2024-06-16"),
    motExpiryDate: new Date("2025-06-15"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2018-06"),
  },
  FJ20WXC: {
    registrationNumber: "FJ20WXC",
    taxStatus: "Taxed",
    taxDueDate: new Date("2025-01-25"),
    motStatus: "Valid",
    make: "TESLA",
    yearOfManufacture: 2020,
    engineCapacity: 0,
    co2Emissions: 0,
    fuelType: "ELECTRIC",
    markedForExport: false,
    colour: "WHITE",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2024-01-25"),
    motExpiryDate: new Date("2025-01-24"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2020-01"),
  },
  GH67NTR: {
    registrationNumber: "GH67NTR",
    taxStatus: "Taxed",
    taxDueDate: new Date("2025-07-30"),
    motStatus: "Valid",
    make: "HONDA",
    yearOfManufacture: 2017,
    engineCapacity: 1498,
    co2Emissions: 125,
    fuelType: "PETROL",
    markedForExport: false,
    colour: "GREY",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2024-07-30"),
    motExpiryDate: new Date("2025-07-29"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2017-07"),
  },
  HJ19VKW: {
    registrationNumber: "HJ19VKW",
    taxStatus: "Taxed",
    taxDueDate: new Date("2024-12-04"),
    motStatus: "Valid",
    make: "NISSAN",
    yearOfManufacture: 2019,
    engineCapacity: 1332,
    co2Emissions: 111,
    fuelType: "PETROL",
    markedForExport: false,
    colour: "RED",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2023-12-04"),
    motExpiryDate: new Date("2024-12-03"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2019-12"),
  },
  JK15BHG: {
    registrationNumber: "JK15BHG",
    taxStatus: "Taxed",
    taxDueDate: new Date("2024-11-20"),
    motStatus: "Valid",
    make: "TOYOTA",
    yearOfManufacture: 2015,
    engineCapacity: 1798,
    co2Emissions: 109,
    fuelType: "HYBRID",
    markedForExport: false,
    colour: "BLUE",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2023-11-20"),
    motExpiryDate: new Date("2024-11-19"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2015-11"),
  },
  KL21XMN: {
    registrationNumber: "KL21XMN",
    taxStatus: "Taxed",
    taxDueDate: new Date("2025-04-14"),
    motStatus: "Valid",
    make: "KIA",
    yearOfManufacture: 2021,
    engineCapacity: 1598,
    co2Emissions: 142,
    fuelType: "PETROL",
    markedForExport: false,
    colour: "BLACK",
    typeApproval: "M1",
    euroStatus: "EURO 6",
    dateOfLastV5CIssued: new Date("2024-04-14"),
    motExpiryDate: new Date("2025-04-13"),
    wheelplan: "2 AXLE RIGID BODY",
    monthOfFirstRegistration: new Date("2021-04"),
  },
}

export const VEHICLE_MODELS: { [key: string]: string } = {
  AE68FWG: "XC60",
  BX19UDF: "Focus",
  CF16TYR: "3 Series",
  DN17YUI: "A4",
  EK18LOP: "C-Class",
  FJ20WXC: "Model 3",
  GH67NTR: "Civic",
  HJ19VKW: "Altima",
  JK15BHG: "Corolla",
  KL21XMN: "Sorento",
}

export const REGISTRATION_NUMBERS: string[] = Object.keys(VEHICLE_DATA)
