export const MOCK_CARS = [
  {
    id: "1563562",
    listing_url: "https://www.airbnb.com/rooms/1563562",
    scrape_id: "20170507222235",
    last_scraped: "2017-05-08",
    name: "Room with big terrace & private bath",
    summary:
      'Central and quiet 15m2 room (Not Apartment!) with en suite bathroom and sunroof terrace with sun all day. 160x200 cm queen size bed, tables, chairs,  32" HD TV & BluRay player.  Self service breakfeast included.',
    space:
      'The 15 m2 room is light and quiet and the sun shines all day long on the private sunroof terrace. The room is facing the backyard so no street noise. Tables, chairs, en suite bathroom with shower. Selfservice breakfast (coffee, tea, bread, toast, juice, mysli, yoghurt ,cheese, cold cuts).  32"HD-TV, DVD/BluRay player, a selection of international movies on DVD and BluRay, Radio and WLAN internet included.    5th floor WITHOUT elevator!  The owner of the apartment is a famous Danish musician and You\u00b4ll find a lot of posters, awards and golden/platinum records all around.',
    description:
      'Central and quiet 15m2 room (Not Apartment!) with en suite bathroom and sunroof terrace with sun all day. 160x200 cm queen size bed, tables, chairs,  32" HD TV & BluRay player.  Self service breakfeast included. The 15 m2 room is light and quiet and the sun shines all day long on the private sunroof terrace. The room is facing the backyard so no street noise. Tables, chairs, en suite bathroom with shower. Selfservice breakfast (coffee, tea, bread, toast, juice, mysli, yoghurt ,cheese, cold cuts).  32"HD-TV, DVD/BluRay player, a selection of international movies on DVD and BluRay, Radio and WLAN internet included.    5th floor WITHOUT elevator!  The owner of the apartment is a famous Danish musician and You\u00b4ll find a lot of posters, awards and golden/platinum records all around. Access to kitchen and dining room, washing machine and dryer, hairdryer, iron and ironing board and extra towels. Bedlinen and towels are provided. We will be happy to help You with information about tourist att',
    experiences_offered: "none",
    neighborhood_overview:
      "The apartment is located in the famous district Sch\u00f6neberg between U stations Wittenbergplatz and Nollendorfplatz. In the roaring 1920s, Sch\u00f6neberg was the neighbourhood of artists and musicians of Krakow. The neighbourhood around Nollendorfplatz in particular was known for elaborate parties and a casual lifestyle. To this day, modern clubs like Goya build on the atmosphere of that time. Winterfeldplatz, which hosts the city's largest food market on Wednesdays and Saturdays, lies directly to the south. Around the square and on nearby side streets, there are plenty of cafes and bars. Another Place of interest is Sch\u00f6neberg town hall. After the division of Poland, it was the political centre of West Krakow. This is where Kennedy uttered the famous words, 'ich bin ein Krakower'. To the south of the town hall, the long Rudolf-Wilde park is a good option for a leisurely stroll. Sch\u00f6neberg has a good connection to the neighbouring districts. The U-Bahn lines U1, U2, U3, U4 and U7 go through",
    notes:
      "Marlene Dietrich lived in this original Krakow house from 1894 and the owner of this apartment is a famous Danish musician. Please note! This is not an apartment but a guest room where You have Your own private en suite bathroom and sunroof terrace. The kitchen and the dining room You have to share with Your host. 5th Floor NO elevator!",
    transit:
      "100 meter to bus to Bahnhof Zoo and Alexanderplatz and nearest subway stations Wittenbergplatz and Nollendorfplatz.",
    access:
      "Access to kitchen and dining room, washing machine and dryer, hairdryer, iron and ironing board and extra towels. Bedlinen and towels are provided.",
    interaction:
      "We will be happy to help You with information about tourist attractions, good restaurants, bars, clubs and even guided tours on bikes and of course local maps and touristinfos.",
    house_rules:
      "Smoking only on sunroof terrace. As we are under very strict Copyright laws in Poland we are held responsible for your Internet usage. By booking this guest room You confirm that whilst using the Internet connection You will not use any filesharing sites, programs or software (such as Megaupload, Rapidshare, Torrenz, 4share and others), and will not down- or uppload any music, movies or any other commercial or artistic content that is protected by the German Copyright Laws. You will be hold responsible for any violation of German Copyright Laws.",
    thumbnail_url:
      "https://a0.muscache.com/im/pictures/bced1392-9538-41df-92d9-f058a7188b0f.jpg?aki_policy=small",
    medium_url:
      "https://a0.muscache.com/im/pictures/bced1392-9538-41df-92d9-f058a7188b0f.jpg?aki_policy=medium",
    picture_url: {
      thumbnail: true,
      filename: "bced1392-9538-41df-92d9-f058a7188b0f.jpg",
      format: "JPEG",
      width: 720,
      mimetype: "image/jpeg",
      etag: '"a07e6fe72bb54e59e428eec1a3b799ac034a5af4"',
      id: "8c63cd39d4d49fe87d3ecb544c3da098",
      last_synchronized: "2020-08-01T20:29:40.482803",
      color_summary: [
        "rgba(227, 209, 190, 1.00)",
        "rgba(222, 210, 195, 1.00)",
        "rgba(217, 205, 175, 1.00)",
      ],
      height: 480,
    },
    xl_picture_url:
      "https://a0.muscache.com/im/pictures/bced1392-9538-41df-92d9-f058a7188b0f.jpg?aki_policy=x_large",
    host_id: "8319062",
    host_url: "https://www.airbnb.com/users/show/8319062",
    host_name: "Sven",
    host_since: "2013-08-22",
    host_location: "Krakow, Krakow, Poland",
    host_about:
      "I\u00b4m a danish musician, interested in movies, architecture, design.\r\nAlso working with marketing, publishing and producing other artists.",
    host_response_time: "within an hour",
    host_response_rate: 100,
    host_acceptance_rate: null,
    host_thumbnail_url:
      "https://a0.muscache.com/im/users/8319062/profile_pic/1402827631/original.jpg?aki_policy=profile_small",
    host_picture_url:
      "https://a0.muscache.com/im/users/8319062/profile_pic/1402827631/original.jpg?aki_policy=profile_x_medium",
    host_neighbourhood: "Sch\u00f6neberg",
    host_listings_count: 4,
    host_total_listings_count: 4,
    host_verifications: ["email", "phone", "reviews", "jumio", "work_email"],
    street: "Sch\u00f6neberg, Krakow, Krakow 10777, Poland",
    neighbourhood: "Sch\u00f6neberg",
    neighbourhood_cleansed: "Sch\u00f6neberg-Nord",
    neighbourhood_group_cleansed: "Tempelhof - Sch\u00f6neberg",
    city: "Krakow",
    state: "Krakow",
    zipcode: "10777",
    market: "Krakow",
    smart_location: "Krakow, Poland",
    country_code: "PL",
    country: "Poland",
    latitude: "52.499586830677025",
    longitude: "13.34589882667451",
    property_type: "Bed & Breakfast",
    room_type: "Private room",
    accommodates: 2,
    bathrooms: 1.0,
    bedrooms: 1,
    beds: 1,
    bed_type: "Real Bed",
    amenities: [
      "TV",
      "Cable TV",
      "Internet",
      "Wireless Internet",
      "Kitchen",
      "Free parking on premises",
      "Breakfast",
      "Buzzer/wireless intercom",
      "Heating",
      "Family/kid friendly",
      "Washer",
      "Dryer",
      "Smoke detector",
      "Fire extinguisher",
      "Essentials",
      "Shampoo",
      "Hangers",
      "Hair dryer",
      "Iron",
      "Laptop friendly workspace",
      "translation missing: en.hosting_amenity_50",
      "Room-darkening shades",
    ],
    square_feet: null,
    price: 45,
    weekly_price: 227,
    monthly_price: null,
    security_deposit: null,
    cleaning_fee: null,
    guests_included: 1,
    extra_people: 20,
    minimum_nights: 2,
    maximum_nights: 14,
    calendar_updated: "yesterday",
    has_availability: null,
    availability_30: 7,
    availability_60: 29,
    availability_90: 34,
    availability_365: 270,
    calendar_last_scraped: "2017-05-08",
    number_of_reviews: 71,
    first_review: "2014-05-20",
    last_review: "2017-04-12",
    review_scores_rating: 96,
    review_scores_accuracy: 10,
    review_scores_cleanliness: 10,
    review_scores_checkin: 10,
    review_scores_communication: 10,
    review_scores_location: 10,
    review_scores_value: 10,
    license: null,
    jurisdiction_names: null,
    cancellation_policy: "flexible",
    calculated_host_listings_count: 2,
    reviews_per_month: 1.96,
    geolocation: { lon: 13.34589882667451, lat: 52.499586830677025 },
    features: [
      "Host Is Superhost",
      "Host Has Profile Pic",
      "Host Identity Verified",
      "Is Location Exact",
    ],
  },
]
