import { z } from "zod"

export const VehicleDetailsScalarFieldEnumSchema = z.enum([
  "id",
  "fromApi",
  "registrationNumber",
  "make",
  "model",
  "colour",
  "yearOfManufacture",
  "taxStatus",
  "taxDueDate",
  "motStatus",
  "motExpiryDate",
  "engineCapacity",
  "co2Emissions",
  "fuelType",
  "markedForExport",
  "typeApproval",
  "wheelplan",
  "artEndDate",
  "monthOfFirstRegistration",
  "euroStatus",
  "dateOfLastV5CIssued",
  "realDrivingEmissions",
  "revenueWeight",
  "ownershipId",
  "createdAt",
  "updatedAt",
])
